env:
    MANIFEST: https://github.com/PitchBlackRecoveryProject/manifest_pb.git -b android-11.0
    OUTPUT: PBRP*.zip
    A3: a3y17lte
    J7X: j7xelte
    J7V: j7velte
    J5Y: j5y17lte
    J7Y: j7y17lte
    J6: j6lte
    A6: a6lte
    J7P: on7xelte

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 240m  
  container:
      image: ubuntu:20.04
      cpu: 8
      memory: 32G
  
  Build-Env-Setup_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - df -h
       - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata
       - ln -sf /usr/share/zoneinfo/Asia/HoChiMinh /etc/localtime
       - apt-get install -y tzdata
       - dpkg-reconfigure --frontend noninteractive tzdata
       - sudo apt update -y && sudo apt install git aria2 curl wget rsync zip unzip lzma cpio ccache neofetch -y
       - sudo apt install python2 -y
       - sudo ln -sf /usr/bin/python2 /usr/bin/python
       - git config --global user.name "Sushrut1101"
       - git config --global user.email "guptasushrut@gmail.com"
       - git clone https://github.com/akhilnarang/scripts.git ~/scripts
       - cd ~/scripts
       - sudo bash setup/android_build_env.sh
       - cd ~
  
  Neofetch_script:
       - neofetch
  
  Storage-Checker_script:
      - df -h
      - lsblk
      - ls -l -a -h


  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - mkdir -p ~/work
      - cd ~/work
      - repo init --depth=1 -u $MANIFEST 
      - repo sync -j16 --force-sync --no-tags --no-clone-bundle
      - cd ~
      - mkdir -p ~/done
      - echo "============================"
      - echo "Syncing Complete!"
      - echo "============================"
  
  
  BuildP-A3_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - cd ~/work
      - make clean
      - git clone https://github.com/ping2109/device_samsung_$A3-twrp.git device/samsung/$A3
      - source build/envsetup.sh
      - . device/samsung/$A3/vendorsetup.sh
      - export ALLOW_MISSING_DEPENDENCIES=true
      - export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
      - export LC_ALL="C"
      - lunch omni_$A3-eng
      - mka recoveryimage -j16
      - cd out/target/product/$A3
      - cp $OUTPUT ~/done
     
  BuildP-J7X_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - cd ~/work
      - make clean
      - git clone https://github.com/ping2109/device_samsung_$J7X-twrp.git device/samsung/$J7X
      - source build/envsetup.sh
      - . device/samsung/$J7X/vendorsetup.sh
      - export ALLOW_MISSING_DEPENDENCIES=true
      - export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
      - export LC_ALL="C"
      - lunch omni_$J7X-eng
      - mka recoveryimage -j16
      - cd out/target/product/$J7X
      - cp $OUTPUT ~/done
      
  BuildP-J7P_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - cd ~/work
      - make clean
      - git clone https://github.com/ping2109/device_samsung_$J7P-twrp.git device/samsung/$J7P
      - source build/envsetup.sh
      - . device/samsung/$J7P/vendorsetup.sh
      - export ALLOW_MISSING_DEPENDENCIES=true
      - export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
      - export LC_ALL="C"
      - lunch omni_$J7P-eng
      - mka recoveryimage -j16
      - cd out/target/product/$J7P
      - cp $OUTPUT ~/done
      
  BuildP-J7Y_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - cd ~/work
      - make clean
      - git clone https://github.com/ping2109/device_samsung_$J7Y-twrp.git device/samsung/$J7Y
      - source build/envsetup.sh
      - . device/samsung/$J7Y/vendorsetup.sh
      - export ALLOW_MISSING_DEPENDENCIES=true
      - export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
      - export LC_ALL="C"
      - lunch omni_$J7Y-eng
      - mka recoveryimage -j16
      - cd out/target/product/$J7Y
      - cp $OUTPUT ~/done
      
  BuildP-J5Y_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - cd ~/work
      - make clean
      - git clone https://github.com/ping2109/device_samsung_$J5Y-twrp.git device/samsung/$J5Y
      - source build/envsetup.sh
      - . device/samsung/$J5Y/vendorsetup.sh
      - export ALLOW_MISSING_DEPENDENCIES=true
      - export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
      - export LC_ALL="C"
      - lunch omni_$J5Y-eng
      - mka recoveryimage -j16
      - cd out/target/product/$J5Y
      - cp $OUTPUT ~/done
      
  BuildP-J6_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - cd ~/work
      - make clean
      - git clone https://github.com/ping2109/device_samsung_$J6-twrp.git device/samsung/$J6
      - source build/envsetup.sh
      - . device/samsung/$J6/vendorsetup.sh
      - export ALLOW_MISSING_DEPENDENCIES=true
      - export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
      - export LC_ALL="C"
      - lunch omni_$J6-eng
      - mka recoveryimage -j16
      - cd out/target/product/$J6
      - cp $OUTPUT ~/done
      
  BuildP-A6_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - cd ~/work
      - make clean
      - git clone https://github.com/ping2109/device_samsung_$A6-twrp.git device/samsung/$A6
      - source build/envsetup.sh
      - . device/samsung/$A6/vendorsetup.sh
      - export ALLOW_MISSING_DEPENDENCIES=true
      - export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
      - export LC_ALL="C"
      - lunch omni_$A6-eng
      - mka recoveryimage -j16
      - cd out/target/product/$A6
      - cp $OUTPUT ~/done
           
  Upload_script:
      - echo "============================"
      - echo "Uploading the Build..."
      - echo "============================"
      - cd ~/done
      - curl -sL https://git.io/file-transfer | sh
      - ls -lh
      - pwd
      - chmod 777 *
      - ./transfer wet * | tee link.txt && echo " "
      - echo " "
      - echo "============================"
      - echo "Build Uploaded!"
      - echo "Please see the link Below-  "
      - echo "----------------------------"
      - cat link.txt && echo " "
      - echo "============================"
