env:
    MANIFEST: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11
    DT_LINK: https://github.com/ping2109/device_xiaomi_spes-twrp2
    DEVICE: spes
    OEM: xiaomi
    DT_PATH: device/$OEM/$DEVICE
    TARGET: bootimage
    EXTRA_CMD: # git clone https://github.com/OrangeFoxRecovery/Avatar.git misc
    OUTPUT: recovery.img
    LUNCH: twrp_spes-eng
    GH_NAME: ${{ secrets.GH_NAME }}
    GH_MAIL: ${{ secrets.GH_MAIL }}
    GH_TOKEN: ${{ secrets.GH_TOKEN }}
    
task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m
  container:
      image: ubuntu:20.04
      
  Build-Env-Setup_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - df -h
       - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata
       - ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
       - apt-get install -y tzdata
       - dpkg-reconfigure --frontend noninteractive tzdata
       - sudo apt update -y && sudo apt install git aria2 curl wget rsync zip unzip lzma cpio ccache neofetch -y
       - sudo apt install python2 -y
       - sudo ln -sf /usr/bin/python2 /usr/bin/python
       - git config --global user.name $GH_NAME
       - git config --global user.email $GH_MAIL
       - git config --global credential.helper store
       - echo "https://$GH_NAME:$GH_TOKEN@github.com" > ~/.git-credentials
       - git clone https://github.com/akhilnarang/scripts.git ~/scripts
       - cd ~/scripts
       - sudo bash setup/android_build_env.sh
       - cd ~
  
  Neofetch_script:
       - neofetch
  
  Storage-Checker_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - mkdir -p ~/work
      - cd ~/work
      - repo init --depth=1 -u $MANIFEST 
      - repo sync -j16 --force-sync --no-tags --no-clone-bundle
      - git clone $DT_LINK $DT_PATH
      - echo "============================"
      - echo "Syncing Complete!"
      - echo "============================"
  
  
  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - cd ~/work
      - $EXTRA_CMD
      - . build/envsetup.sh
      - # . $DT_PATH/vendorsetup.sh
      - lunch $LUNCH
      - export ALLOW_MISSING_DEPENDENCIES=true
      - mka -j16 $TARGET
     
  Upload_script:
      - echo "============================"
      - echo "Uploading the Build..."
      - echo "============================"
      - cd ~/work
      - cd out/target/product/"$DEVICE"
      - ls -lh
      - pwd
      - chmod 777 *
      - curl --upload-file $(echo $OUTPUT) https://transfer.sh | tee link.txt && echo " "
      - echo " "
      - echo "============================"
      - echo "Build Uploaded!"
      - echo "Please see the link Below-  "
      - echo "----------------------------"
      - cat link.txt && echo " "
      - echo "============================"
        

